FROM python:3.13

WORKDIR /app

#RUN apt-get update  \
#    && apt-get install -y build-essential --no-install-recommends  \
#    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uwsgi==2.0.29

COPY ./wsgi.py ./infra/uwsgi.ini ./

CMD ["uwsgi", "--ini", "uwsgi.ini"]
